wandb_version: 1

optimizer:
  desc: null
  value: adam
model:
  desc: null
  value: wgan gp
epoch:
  desc: null
  value: '1000'
batch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708615400.724433
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
